import torch, numpy as np, cv2, os
from models.semr_physics_pro import SEMRPhysicsPro
from utils.degradation import generate_sem_pair
from skimage.metrics import peak_signal_noise_ratio, structural_similarity

def edge_preservation(pred, target):
    pred_grad = np.gradient(pred)
    target_grad = np.gradient(target)
    return np.corrcoef(pred_grad[0].flat, target_grad[0].flat)[0, 1]

def main():
    device = torch.device('cpu')
    model = SEMRPhysicsPro(scale=2, dim=12, num_blocks=[2,2,2,2], heads=4).to(device)
    model.load_state_dict(torch.load('pretrained/best_light.pth', map_location=device))
    model.eval()

    # Load clean original image (the one generated by test_sample.py)
    clean = cv2.imread('results/clean_original.png', cv2.IMREAD_GRAYSCALE).astype(np.float32) / 255.0
    lr, _ = generate_sem_pair(clean, scale=4)   # same degradation

    lr_t = torch.from_numpy(lr).float().unsqueeze(0).unsqueeze(0)
    with torch.no_grad():
        hr_pred, _ = model(lr_t)
    hr_pred = hr_pred.squeeze().numpy()
    hr_pred = np.clip(hr_pred, 0, 1)

    # Metrics
    psnr = peak_signal_noise_ratio(clean, hr_pred, data_range=1)
    ssim = structural_similarity(clean, hr_pred, data_range=1)
    eps = edge_preservation(hr_pred, clean)

    print(f"PSNR: {psnr:.2f} dB")
    print(f"SSIM: {ssim:.4f}")
    print(f"Edge Preservation Score: {eps:.4f}")

    # Save restored
    cv2.imwrite('results/eval_restored.png', (hr_pred*255).astype(np.uint8))

if __name__ == '__main__':
    os.makedirs('results', exist_ok=True)
    main()